adding inner shell to spherical surfaces
evanhanders/plotpal pull request #9
Opened 2024-03-15 18:57 UTC by jorafb

2024-03-15 19:05 UTC, evanhanders reviewed
It would be super helpful if you could add an example of an inner-and-outer-shell convection script to the examples section and include a script that plots stuff up!!

2024-03-15 19:05 UTC, evanhanders commented on plotpal/volumes.py
> +    def __init__(self, equator, left_meridian, right_meridian, inner_shell, outer_shell, vector_ind=None, view=0,
Can you swap these around and set inner_shell=0 by default?

2024-03-15 19:05 UTC, evanhanders commented on plotpal/volumes.py
> +        self.data_dicts = [self.out_data, self.in_data, self.mer_data, self.eq_data]
put this in an if statement that only includes in_data if the inner radius is > 0

2024-03-15 19:05 UTC, evanhanders commented on plotpal/volumes.py
> +                for task in sp.equator + sp.left_meridian + sp.right_meridian + [sp.inner_shell,sp.outer_shell]:
probably we should make this a bit better (i did it bad in the first places)

Add a line above that is tasks = sp.equator + sp.left_meridian + sp.right_meridian + [sp.outer_shell]
then if inner raidius > 0 do tasks += [sp.outer_shell]
then do for task in tasks:

2024-03-15 23:17 UTC, evanhanders commented on plotpal/volumes.py
> +        shell_field = dsets[self.inner_shell][ni].squeeze()
I think this code block will throw an error if self.inner_shell is None; let's add an if-statement and indent here.

2024-03-15 23:17 UTC, evanhanders commented on plotpal/volumes.py
> +        if self.r_inner>0:
change to if shell_inner is None

2024-03-18 15:51 UTC, evanhanders requested changes
Almost ready to merge! A couple more small changes to make and then we can merge

2024-03-18 15:51 UTC, evanhanders commented on examples/d3/ivp_shell_convection/plot_pyvista_sphere.py
> +plotter.add_sphere(equator='flux(equator)',left_meridian='flux_phi_start', right_meridian='flux_phi_end', inner_shell='flux_r_inner',outer_shell='flux_r_outer', view=0, cmap='cividis', label="X", r_i
Would be good to change the label here since 'X' isn't in the original dedalus script

2024-03-18 15:51 UTC, evanhanders commented on examples/d3/ivp_shell_convection/shell_convection.py
> +"""
Please add a line here noting that "This script is directly copied from the Dedalus 3 repository, see https://github.com/DedalusProject/dedalus/tree/master/examples/ivp_shell_convection"

2024-03-19 14:06 UTC, jorafb commented
Done, I think that should be it. Thanks for your suggestions :)

2024-03-19 14:45 UTC, evanhanders approved these changes

2024-03-19 14:46 UTC, merged